'use client'
import { useState, useEffect } from 'react'
const m: any = { fontFamily: '"IBM Plex Mono", monospace' }
function fmt(n: number) { return n>=1000000?'$'+(n/1000000).toFixed(2)+'M':n>=1000?'$'+Math.round(n/1000)+'k':'$'+n.toLocaleString() }
const STATUSES = ['new','contacted','verified','filed','recovered','closed']
export default function AdminSurplus() {
  const [claims,setClaims]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [filter,setFilter]=useState('new')
  useEffect(()=>{ async function load() { setLoading(true); const {createBrowserClient}=await import('@supabase/ssr'); const db=createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!); let q=db.from('surplus_claims').select('*, overages(*)').order('created_at',{ascending:false}); if(filter) q=q.eq('status',filter); const{data}=await q.limit(100); setClaims(data||[]); setLoading(false) } load() },[filter])
  return (<div style={{...m,background:'#0a0a0a',minHeight:'100vh',padding:'32px 24px',color:'#e0e0e0'}}><div style={{maxWidth:'1100px',margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:'32px'}}><div><div style={{fontSize:'20px',fontWeight:700,color:'#fff',marginBottom:'4px'}}>Surplus Claims</div><div style={{fontSize:'12px',color:'#555'}}>{claims.length} {filter||'total'} claims</div></div><div style={{display:'flex',gap:'16px'}}><a href="/surplus" style={{...m,fontSize:'12px',color:'#3b82f6',textDecoration:'none'}}>Public search</a><a href="/dashboard" style={{...m,fontSize:'12px',color:'#555',textDecoration:'none'}}>Property Intel</a></div></div><div style={{display:'flex',gap:'8px',marginBottom:'24px',flexWrap:'wrap' as any}}>{['all',...STATUSES].map(s=>(<button key={s} onClick={()=>setFilter(s==='all'?'':s)} style={{...m,padding:'6px 14px',fontSize:'11px',border:'1px solid',borderColor:filter===(s==='all'?'':s)?'#fff':'#333',background:'none',color:filter===(s==='all'?'':s)?'#fff':'#555',cursor:'pointer',textTransform:'uppercase' as any,letterSpacing:'0.1em'}}>{s}</button>))}</div>{loading?<div style={{color:'#555',padding:'40px 0'}}>Loading...</div>:claims.length===0?<div style={{color:'#555',padding:'40px 0'}}>No {filter||''} claims yet.</div>:(<div style={{display:'flex',flexDirection:'column',gap:'12px'}}>{claims.map(c=>{const ov=c.overages; return(<div key={c.id} style={{border:'1px solid #1a1a1a',padding:'20px 24px',background:'#0d0d0d',display:'grid',gridTemplateColumns:'1.5fr 1.5fr 1fr auto',gap:'24px',alignItems:'start'}}><div><div style={{fontSize:'14px',color:'#fff',fontWeight:700,marginBottom:'4px'}}>{c.claimant_name}</div><a href={'mailto:'+c.claimant_email} style={{...m,fontSize:'12px',color:'#3b82f6',display:'block',marginBottom:'2px',textDecoration:'none'}}>{c.claimant_email}</a><div style={{fontSize:'12px',color:'#666'}}>{c.claimant_phone||'No phone'}</div>{c.message&&<div style={{fontSize:'11px',color:'#555',marginTop:'8px',fontStyle:'italic'}}>{c.message.slice(0,120)}</div>}</div><div>{ov&&<><div style={{fontSize:'13px',color:'#ccc',marginBottom:'4px'}}>{ov.owner_name}</div><div style={{fontSize:'12px',color:'#666',marginBottom:'2px'}}>{ov.property_address}, {ov.state}</div><div style={{fontSize:'11px',color:'#444'}}>{ov.county} County</div></>}</div><div>{ov&&<div style={{fontSize:'22px',fontWeight:700,color:'#4ade80',marginBottom:'4px'}}>{fmt(ov.surplus_amount)}</div>}<div style={{fontSize:'11px',color:'#555'}}>{new Date(c.created_at).toLocaleDateString()}</div></div><div><span style={{fontSize:'10px',background:c.status==='new'?'#1e3a5f':c.status==='recovered'?'#14532d':'#1a1a1a',color:c.status==='new'?'#60a5fa':c.status==='recovered'?'#4ade80':'#666',padding:'4px 10px',textTransform:'uppercase' as any,letterSpacing:'0.1em'}}>{c.status}</span></div></div>)})}</div>)}</div></div>)
}
