export interface BusinessListing {
  id: number;
  title: string;
  askingPrice: number;
  revenue: number | null;
  sdeCashFlow: number | null;
  ebitda: number | null;
  industry: string;
  subIndustry: string | null;
  city: string;
  state: string;
  zip: string;
  brokerName: string | null;
  brokerCompany: string | null;
  brokerPhone: string | null;
  brokerEmail: string | null;
  reasonForSale: string | null;
  description: string | null;
  employees: number | null;
  yearEstablished: number | null;
  isFranchise: boolean;
  isSemiAbsentee: boolean;
  hasRecurringRevenue: boolean;
  sourcePlatform: string;
  sourceUrl: string | null;
  daysListed: number;
  status: 'active' | 'under_loi' | 'sold';
  askingMultiple: number | null;
  score: number;
  flags: { stale?: boolean; overpriced?: boolean; incomplete?: boolean };
  notes: string;
}

export const bizIndustries = [
  { value: 'all', label: 'All Industries' },
  { value: 'Laundromat', label: 'Laundromat' },
  { value: 'Auto', label: 'Auto' },
  { value: 'Restaurant/Food', label: 'Restaurant/Food' },
  { value: 'HVAC/Trades', label: 'HVAC/Trades' },
  { value: 'Franchise', label: 'Franchise' },
  { value: 'Retail', label: 'Retail' },
  { value: 'Tech/SaaS', label: 'Tech/SaaS' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Services', label: 'Services' },
] as const;

export const bizStatuses = [
  { value: 'all', label: 'All' },
  { value: 'active', label: 'Active' },
  { value: 'under_loi', label: 'Under LOI' },
  { value: 'sold', label: 'Sold' },
] as const;

export const bizSortOptions = [
  { value: 'multiple', label: 'Multiple' },
  { value: 'sde', label: 'SDE' },
  { value: 'revenue', label: 'Revenue' },
  { value: 'price', label: 'Price' },
  { value: 'daysListed', label: 'Days Listed' },
  { value: 'score', label: 'Score' },
] as const;

export function calculateBuyBoxScore(biz: BusinessListing): number {
  let score = 0;
  if (biz.askingMultiple != null) {
    if (biz.askingMultiple < 3) score += 25;
    else if (biz.askingMultiple <= 4) score += 15;
  }
  if (biz.hasRecurringRevenue) score += 20;
  if (biz.isSemiAbsentee) score += 15;
  if (biz.sdeCashFlow != null && biz.sdeCashFlow > 150000) score += 15;
  if (biz.yearEstablished != null && (new Date().getFullYear() - biz.yearEstablished) > 5) score += 10;
  if (biz.employees != null && biz.employees < 10) score += 5;
  // +5 for franchise or non-franchise (always +5)
  score += 5;
  if (biz.askingPrice < 2000000) score += 5;
  return score;
}

export function computeFlags(biz: BusinessListing): BusinessListing['flags'] {
  return {
    stale: biz.daysListed > 90,
    overpriced: biz.askingMultiple != null && biz.askingMultiple > 5,
    incomplete: biz.sdeCashFlow == null || biz.revenue == null,
  };
}

function make(partial: Omit<BusinessListing, 'askingMultiple' | 'score' | 'flags'>): BusinessListing {
  const askingMultiple = partial.sdeCashFlow ? +(partial.askingPrice / partial.sdeCashFlow).toFixed(1) : null;
  const base = { ...partial, askingMultiple, score: 0, flags: {} };
  base.score = calculateBuyBoxScore(base);
  base.flags = computeFlags(base);
  return base;
}

export const mockBizListings: BusinessListing[] = [
  make({
    id: 1,
    title: "CleanSpin Laundromat — 3 Locations",
    askingPrice: 650000,
    revenue: 420000,
    sdeCashFlow: 260000,
    ebitda: 235000,
    industry: "Laundromat",
    subIndustry: "Coin/Card Operated",
    city: "Somerville",
    state: "MA",
    zip: "02143",
    brokerName: "Jeff Paulson",
    brokerCompany: "Sunbelt Business Brokers",
    brokerPhone: "(617) 849-2200",
    brokerEmail: "jpaulson@sunbelt.com",
    reasonForSale: "Retirement",
    description: "Three coin-operated laundromats in high-traffic locations. All locations have been upgraded with new Speed Queen equipment in 2022. Strong recurring revenue with card payment systems.",
    employees: 3,
    yearEstablished: 2011,
    isFranchise: false,
    isSemiAbsentee: true,
    hasRecurringRevenue: true,
    sourcePlatform: "BizBuySell",
    sourceUrl: "https://bizbuysell.com/listing/cleanspin",
    daysListed: 18,
    status: "active",
    notes: "",
  }),
  make({
    id: 2,
    title: "Tony's Auto Body & Repair",
    askingPrice: 425000,
    revenue: 780000,
    sdeCashFlow: 185000,
    ebitda: 160000,
    industry: "Auto",
    subIndustry: "Body Shop & Mechanical",
    city: "Brockton",
    state: "MA",
    zip: "02301",
    brokerName: "Mark Tessier",
    brokerCompany: "Tessier Business Sales",
    brokerPhone: "(508) 580-9100",
    brokerEmail: "mark@tessierbiz.com",
    reasonForSale: "Health issues",
    description: "Full-service auto body and mechanical repair. DRP agreements with 3 major insurance companies. 8-bay shop with paint booth on 0.5 acre lot.",
    employees: 7,
    yearEstablished: 2003,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: false,
    sourcePlatform: "BizBuySell",
    sourceUrl: null,
    daysListed: 45,
    status: "active",
    notes: "",
  }),
  make({
    id: 3,
    title: "Northeast HVAC Services",
    askingPrice: 1200000,
    revenue: 1800000,
    sdeCashFlow: 420000,
    ebitda: 380000,
    industry: "HVAC/Trades",
    subIndustry: "Residential & Commercial HVAC",
    city: "Worcester",
    state: "MA",
    zip: "01605",
    brokerName: "Dan McCarthy",
    brokerCompany: "Murphy Business Sales",
    brokerPhone: "(508) 756-3300",
    brokerEmail: "dmccarthy@murphybusiness.com",
    reasonForSale: "Partner buyout",
    description: "Established HVAC company serving residential and light commercial. 450+ service agreement customers providing recurring revenue. Licensed in MA, RI, CT.",
    employees: 12,
    yearEstablished: 2008,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: true,
    sourcePlatform: "BizBuySell",
    sourceUrl: "https://bizbuysell.com/listing/ne-hvac",
    daysListed: 32,
    status: "active",
    notes: "",
  }),
  make({
    id: 4,
    title: "Subway Franchise — Downtown Location",
    askingPrice: 189000,
    revenue: 340000,
    sdeCashFlow: 72000,
    ebitda: 58000,
    industry: "Restaurant/Food",
    subIndustry: "QSR Franchise",
    city: "Quincy",
    state: "MA",
    zip: "02169",
    brokerName: "Linda Tran",
    brokerCompany: "Franchise Resales Inc.",
    brokerPhone: "(617) 328-5500",
    brokerEmail: "ltran@franchiseresales.com",
    reasonForSale: "Relocating out of state",
    description: "Subway franchise in high foot traffic downtown location near T station. Lease has 6 years remaining with option to renew.",
    employees: 8,
    yearEstablished: 2017,
    isFranchise: true,
    isSemiAbsentee: false,
    hasRecurringRevenue: false,
    sourcePlatform: "BizBuySell",
    sourceUrl: null,
    daysListed: 65,
    status: "active",
    notes: "",
  }),
  make({
    id: 5,
    title: "Sparkle Clean Commercial Janitorial",
    askingPrice: 380000,
    revenue: 620000,
    sdeCashFlow: 195000,
    ebitda: 172000,
    industry: "Services",
    subIndustry: "Commercial Cleaning",
    city: "Framingham",
    state: "MA",
    zip: "01701",
    brokerName: "Amy Chen",
    brokerCompany: "Transworld Business Advisors",
    brokerPhone: "(508) 879-4400",
    brokerEmail: "achen@tworld.com",
    reasonForSale: "Pursuing other ventures",
    description: "Commercial janitorial company with 35 recurring monthly contracts. Services office buildings, medical facilities, and retail spaces. All equipment included.",
    employees: 18,
    yearEstablished: 2014,
    isFranchise: false,
    isSemiAbsentee: true,
    hasRecurringRevenue: true,
    sourcePlatform: "BizBuySell",
    sourceUrl: "https://bizbuysell.com/listing/sparkle-clean",
    daysListed: 12,
    status: "active",
    notes: "",
  }),
  make({
    id: 6,
    title: "Bay State Manufacturing — CNC Shop",
    askingPrice: 2800000,
    revenue: 3200000,
    sdeCashFlow: 680000,
    ebitda: 620000,
    industry: "Manufacturing",
    subIndustry: "CNC Machining",
    city: "Taunton",
    state: "MA",
    zip: "02780",
    brokerName: "Robert Gill",
    brokerCompany: "Gill & Associates",
    brokerPhone: "(508) 822-7700",
    brokerEmail: "rgill@gilladvisors.com",
    reasonForSale: "Retirement after 30 years",
    description: "Precision CNC machining shop with 12 machines. Defense and aerospace contracts. AS9100 certified. Owns 15,000 sq ft building on 1.5 acres.",
    employees: 22,
    yearEstablished: 1994,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: true,
    sourcePlatform: "Broker Direct",
    sourceUrl: null,
    daysListed: 55,
    status: "active",
    notes: "Real estate included in price.",
  }),
  make({
    id: 7,
    title: "Quick Lube Express — Jiffy Lube Franchise",
    askingPrice: 520000,
    revenue: 680000,
    sdeCashFlow: 165000,
    ebitda: 142000,
    industry: "Auto",
    subIndustry: "Oil Change / Quick Lube",
    city: "Nashua",
    state: "NH",
    zip: "03060",
    brokerName: "Brian Walsh",
    brokerCompany: "Empire Business Brokers",
    brokerPhone: "(603) 888-2100",
    brokerEmail: "bwalsh@empirebrokers.com",
    reasonForSale: "Buying larger franchise",
    description: "Jiffy Lube franchise with strong brand recognition. High-traffic Route 101A location. 4-bay facility with pit service.",
    employees: 6,
    yearEstablished: 2015,
    isFranchise: true,
    isSemiAbsentee: true,
    hasRecurringRevenue: false,
    sourcePlatform: "BizBuySell",
    sourceUrl: null,
    daysListed: 28,
    status: "active",
    notes: "",
  }),
  make({
    id: 8,
    title: "Boston Digital Marketing Agency",
    askingPrice: 750000,
    revenue: 520000,
    sdeCashFlow: 180000,
    ebitda: 155000,
    industry: "Tech/SaaS",
    subIndustry: "Digital Marketing",
    city: "Cambridge",
    state: "MA",
    zip: "02139",
    brokerName: "Nicole Park",
    brokerCompany: "Quiet Light Brokerage",
    brokerPhone: "(617) 876-9900",
    brokerEmail: "npark@quietlight.com",
    reasonForSale: "Founder pursuing startup",
    description: "Boutique digital marketing agency specializing in B2B SaaS. 85% of revenue is recurring via retainer contracts. Fully remote team. Strong pipeline.",
    employees: 5,
    yearEstablished: 2018,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: true,
    sourcePlatform: "Quiet Light",
    sourceUrl: "https://quietlight.com/listing/boston-digital",
    daysListed: 15,
    status: "active",
    notes: "",
  }),
  make({
    id: 9,
    title: "Oceanside Physical Therapy",
    askingPrice: 890000,
    revenue: 1100000,
    sdeCashFlow: 320000,
    ebitda: 280000,
    industry: "Healthcare",
    subIndustry: "Physical Therapy",
    city: "Plymouth",
    state: "MA",
    zip: "02360",
    brokerName: "Steve Romano",
    brokerCompany: "Romano Healthcare Advisors",
    brokerPhone: "(508) 746-5500",
    brokerEmail: "sromano@romanoadvisors.com",
    reasonForSale: "Moving to Florida",
    description: "Two-location physical therapy practice. Credentialed with all major insurers. 3 treating PTs + support staff. Strong referral network with local orthopedic surgeons.",
    employees: 9,
    yearEstablished: 2012,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: true,
    sourcePlatform: "Broker Direct",
    sourceUrl: null,
    daysListed: 40,
    status: "active",
    notes: "",
  }),
  make({
    id: 10,
    title: "Overpriced Pizza Palace",
    askingPrice: 950000,
    revenue: 380000,
    sdeCashFlow: 110000,
    ebitda: 85000,
    industry: "Restaurant/Food",
    subIndustry: "Pizzeria",
    city: "Lowell",
    state: "MA",
    zip: "01852",
    brokerName: "Phil Doucette",
    brokerCompany: "Doucette Realty",
    brokerPhone: "(978) 459-1100",
    brokerEmail: "phil@doucetterealty.com",
    reasonForSale: "Burnout",
    description: "Family pizzeria with 40 seats. Liquor license included. Delivery and dine-in. Prime downtown location.",
    employees: 12,
    yearEstablished: 2005,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: false,
    sourcePlatform: "BizBuySell",
    sourceUrl: null,
    daysListed: 135,
    status: "active",
    notes: "Way overpriced. Multiple is 8.6x.",
  }),
  make({
    id: 11,
    title: "Rhode Island E-Commerce Brand",
    askingPrice: 475000,
    revenue: null,
    sdeCashFlow: null,
    ebitda: null,
    industry: "Retail",
    subIndustry: "E-Commerce",
    city: "Providence",
    state: "RI",
    zip: "02903",
    brokerName: "Jason Medeiros",
    brokerCompany: "Digital Exits",
    brokerPhone: "(401) 621-3300",
    brokerEmail: "jmedeiros@digitalexits.com",
    reasonForSale: null,
    description: "Amazon FBA business selling pet products. Listing says 'strong revenue' but no financials disclosed yet. NDA required.",
    employees: 2,
    yearEstablished: 2020,
    isFranchise: false,
    isSemiAbsentee: true,
    hasRecurringRevenue: false,
    sourcePlatform: "Digital Exits",
    sourceUrl: null,
    daysListed: 95,
    status: "active",
    notes: "Requested financials — waiting on NDA.",
  }),
  make({
    id: 12,
    title: "New England Pest Control",
    askingPrice: 580000,
    revenue: 720000,
    sdeCashFlow: 220000,
    ebitda: 195000,
    industry: "Services",
    subIndustry: "Pest Control",
    city: "Marlborough",
    state: "MA",
    zip: "01752",
    brokerName: "Gary Plante",
    brokerCompany: "Plante Business Group",
    brokerPhone: "(508) 485-6600",
    brokerEmail: "gplante@plantebiz.com",
    reasonForSale: "Retirement",
    description: "Residential and commercial pest control serving MetroWest and Worcester County. 280+ recurring monthly/quarterly service agreements. Two service trucks and all equipment included.",
    employees: 5,
    yearEstablished: 2009,
    isFranchise: false,
    isSemiAbsentee: true,
    hasRecurringRevenue: true,
    sourcePlatform: "BizBuySell",
    sourceUrl: "https://bizbuysell.com/listing/ne-pest",
    daysListed: 22,
    status: "active",
    notes: "",
  }),
  make({
    id: 13,
    title: "Dunkin' Donuts — 2 Units",
    askingPrice: 1400000,
    revenue: 1650000,
    sdeCashFlow: 280000,
    ebitda: 245000,
    industry: "Restaurant/Food",
    subIndustry: "QSR Franchise",
    city: "Fall River",
    state: "MA",
    zip: "02720",
    brokerName: "Linda Tran",
    brokerCompany: "Franchise Resales Inc.",
    brokerPhone: "(617) 328-5500",
    brokerEmail: "ltran@franchiseresales.com",
    reasonForSale: "Consolidating portfolio",
    description: "Two Dunkin' locations with drive-throughs. Both recently remodeled to Next Gen format. Strong morning traffic. Combined SDE of $280K.",
    employees: 24,
    yearEstablished: 2010,
    isFranchise: true,
    isSemiAbsentee: false,
    hasRecurringRevenue: false,
    sourcePlatform: "Franchise Resales",
    sourceUrl: null,
    daysListed: 50,
    status: "active",
    notes: "",
  }),
  make({
    id: 14,
    title: "Cape Cod Landscaping & Snow Removal",
    askingPrice: 320000,
    revenue: 480000,
    sdeCashFlow: 155000,
    ebitda: 130000,
    industry: "Services",
    subIndustry: "Landscaping",
    city: "Wareham",
    state: "MA",
    zip: "02571",
    brokerName: "Tim Kenney",
    brokerCompany: "Kenney & Associates",
    brokerPhone: "(508) 295-2200",
    brokerEmail: "tim@kenneyassoc.com",
    reasonForSale: "Relocating",
    description: "Year-round revenue: landscaping April-November, snow removal December-March. 120 residential and 15 commercial contracts. Full fleet of equipment included.",
    employees: 6,
    yearEstablished: 2013,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: true,
    sourcePlatform: "BizBuySell",
    sourceUrl: null,
    daysListed: 8,
    status: "active",
    notes: "",
  }),
  make({
    id: 15,
    title: "Merrimack Valley Dental Practice",
    askingPrice: 1850000,
    revenue: 1400000,
    sdeCashFlow: null,
    ebitda: null,
    industry: "Healthcare",
    subIndustry: "Dental",
    city: "Andover",
    state: "MA",
    zip: "01810",
    brokerName: "Dr. Alan Schwartz",
    brokerCompany: "Professional Practice Sales",
    brokerPhone: "(781) 239-8800",
    brokerEmail: "aschwartz@ppsales.com",
    reasonForSale: "Retirement",
    description: "Established general dentistry practice with 2,800 active patients. 5 operatories in modern 2,400 sq ft suite. Digital X-rays and intraoral cameras.",
    employees: 7,
    yearEstablished: 1998,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: true,
    sourcePlatform: "Broker Direct",
    sourceUrl: null,
    daysListed: 75,
    status: "active",
    notes: "Need to get SDE info from broker.",
  }),
  make({
    id: 16,
    title: "ProFlow Plumbing Co.",
    askingPrice: 890000,
    revenue: 1250000,
    sdeCashFlow: 350000,
    ebitda: 310000,
    industry: "HVAC/Trades",
    subIndustry: "Plumbing",
    city: "Newton",
    state: "MA",
    zip: "02458",
    brokerName: "Dan McCarthy",
    brokerCompany: "Murphy Business Sales",
    brokerPhone: "(508) 756-3300",
    brokerEmail: "dmccarthy@murphybusiness.com",
    reasonForSale: "Owner retiring at 65",
    description: "Residential and commercial plumbing serving Greater Boston. Strong reputation with 4.9 Google rating and 380+ reviews. 5 service vans and all tools included.",
    employees: 8,
    yearEstablished: 2006,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: false,
    sourcePlatform: "BizBuySell",
    sourceUrl: "https://bizbuysell.com/listing/proflow",
    daysListed: 35,
    status: "under_loi",
    notes: "LOI submitted — waiting on seller response.",
  }),
  make({
    id: 17,
    title: "SudsMaster Coin Laundry",
    askingPrice: 275000,
    revenue: 180000,
    sdeCashFlow: 105000,
    ebitda: 92000,
    industry: "Laundromat",
    subIndustry: "Coin/Card Operated",
    city: "Lawrence",
    state: "MA",
    zip: "01841",
    brokerName: "Phil Doucette",
    brokerCompany: "Doucette Realty",
    brokerPhone: "(978) 459-1100",
    brokerEmail: "phil@doucetterealty.com",
    reasonForSale: "Owner moving abroad",
    description: "Single location coin laundry in dense residential area. 30 washers and 24 dryers. Card payment system installed 2023.",
    employees: 1,
    yearEstablished: 2016,
    isFranchise: false,
    isSemiAbsentee: true,
    hasRecurringRevenue: true,
    sourcePlatform: "BizBuySell",
    sourceUrl: null,
    daysListed: 20,
    status: "active",
    notes: "",
  }),
  make({
    id: 18,
    title: "Struggling Print Shop",
    askingPrice: 150000,
    revenue: 210000,
    sdeCashFlow: 55000,
    ebitda: 40000,
    industry: "Services",
    subIndustry: "Printing",
    city: "New Bedford",
    state: "MA",
    zip: "02740",
    brokerName: "Maria Santos",
    brokerCompany: "SouthCoast Business Sales",
    brokerPhone: "(508) 999-1200",
    brokerEmail: "msantos@scbiz.com",
    reasonForSale: "Declining industry",
    description: "Commercial print shop with digital and offset capabilities. Revenue declining 5-10% annually. Good equipment but industry headwinds.",
    employees: 3,
    yearEstablished: 2001,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: false,
    sourcePlatform: "BizBuySell",
    sourceUrl: null,
    daysListed: 200,
    status: "active",
    notes: "Very stale. Revenue declining.",
  }),
  make({
    id: 19,
    title: "Boston Harbor Boat Tours",
    askingPrice: 495000,
    revenue: 580000,
    sdeCashFlow: 175000,
    ebitda: 150000,
    industry: "Services",
    subIndustry: "Tourism",
    city: "Boston",
    state: "MA",
    zip: "02110",
    brokerName: "Jeff Paulson",
    brokerCompany: "Sunbelt Business Brokers",
    brokerPhone: "(617) 849-2200",
    brokerEmail: "jpaulson@sunbelt.com",
    reasonForSale: "Buying larger operation",
    description: "Harbor boat tour company operating 3 vessels. Seasonal (April–October) but very profitable during season. Established online booking system with strong TripAdvisor reviews.",
    employees: 8,
    yearEstablished: 2015,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: false,
    sourcePlatform: "Sunbelt",
    sourceUrl: null,
    daysListed: 42,
    status: "active",
    notes: "Seasonal business — verify off-season costs.",
  }),
  make({
    id: 20,
    title: "MedStaff Temp Agency",
    askingPrice: 3200000,
    revenue: 4500000,
    sdeCashFlow: 520000,
    ebitda: 475000,
    industry: "Healthcare",
    subIndustry: "Staffing",
    city: "Waltham",
    state: "MA",
    zip: "02451",
    brokerName: "Nicole Park",
    brokerCompany: "Quiet Light Brokerage",
    brokerPhone: "(617) 876-9900",
    brokerEmail: "npark@quietlight.com",
    reasonForSale: "PE rollup",
    description: "Medical staffing agency placing nurses, CNAs, and allied health professionals. Contracts with 45+ healthcare facilities across New England. Strong margins on travel nursing placements.",
    employees: 14,
    yearEstablished: 2011,
    isFranchise: false,
    isSemiAbsentee: false,
    hasRecurringRevenue: true,
    sourcePlatform: "Quiet Light",
    sourceUrl: null,
    daysListed: 60,
    status: "active",
    notes: "",
  }),
];
