export interface MarketIndex {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePct: number;
  sparkline: number[];
}

export const marketIndexes: MarketIndex[] = [
  {
    symbol: "SPX",
    name: "S&P 500",
    price: 5248.49,
    change: 22.78,
    changePct: 0.44,
    sparkline: [5180, 5195, 5210, 5190, 5225, 5235, 5248],
  },
  {
    symbol: "NDX",
    name: "Nasdaq",
    price: 16384.47,
    change: -45.12,
    changePct: -0.27,
    sparkline: [16450, 16420, 16380, 16410, 16395, 16370, 16384],
  },
  {
    symbol: "DJI",
    name: "Dow",
    price: 39807.37,
    change: 134.21,
    changePct: 0.34,
    sparkline: [39600, 39650, 39700, 39680, 39750, 39790, 39807],
  },
  {
    symbol: "RUT",
    name: "Russell 2K",
    price: 2075.61,
    change: -8.43,
    changePct: -0.4,
    sparkline: [2090, 2085, 2080, 2078, 2072, 2070, 2075],
  },
  {
    symbol: "TNX",
    name: "10Y Yield",
    price: 4.218,
    change: -0.032,
    changePct: -0.75,
    sparkline: [4.28, 4.26, 4.25, 4.24, 4.23, 4.22, 4.218],
  },
  {
    symbol: "VIX",
    name: "VIX",
    price: 14.32,
    change: 0.87,
    changePct: 6.47,
    sparkline: [13.2, 13.5, 13.8, 14.0, 13.9, 14.1, 14.32],
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    price: 69421.0,
    change: 1247.0,
    changePct: 1.83,
    sparkline: [67800, 68100, 68500, 68200, 69000, 69200, 69421],
  },
  {
    symbol: "GC",
    name: "Gold",
    price: 2338.4,
    change: 12.6,
    changePct: 0.54,
    sparkline: [2310, 2315, 2322, 2328, 2330, 2335, 2338],
  },
  {
    symbol: "CL",
    name: "Oil (WTI)",
    price: 78.61,
    change: -0.84,
    changePct: -1.06,
    sparkline: [80.2, 79.8, 79.5, 79.2, 79.0, 78.8, 78.61],
  },
];

export interface RateSnapshot {
  product: string;
  rate: number;
  lender: string;
  updatedAt: string;
}

export const rateSnapshots: RateSnapshot[] = [
  { product: "30yr Fixed", rate: 6.25, lender: "First Credit Union", updatedAt: "2h ago" },
  { product: "15yr Fixed", rate: 5.625, lender: "PNC Bank", updatedAt: "4h ago" },
  { product: "5/1 ARM", rate: 5.875, lender: "Rockland Trust", updatedAt: "1d ago" },
  { product: "HELOC", rate: 7.99, lender: "Eastern Bank", updatedAt: "3h ago" },
];

export interface OpportunityItem {
  id: number;
  type: "business" | "property";
  title: string;
  price: number;
  metric: string;
  metricLabel: string;
  city: string;
  daysListed: number;
  sourceUrl?: string;
}

export const opportunities: OpportunityItem[] = [
  {
    id: 1,
    type: "property",
    title: "4-Unit Multifamily",
    price: 320000,
    metric: "8.2%",
    metricLabel: "Cap Rate",
    city: "Brockton, MA",
    daysListed: 3,
    sourceUrl: "https://www.loopnet.com/listing/brockton-ma/1",
  },
  {
    id: 2,
    type: "business",
    title: "Coin Laundromat",
    price: 185000,
    metric: "2.8x",
    metricLabel: "Multiple",
    city: "Quincy, MA",
    daysListed: 5,
    sourceUrl: "https://www.bizbuysell.com/listing/coin-laundromat",
  },
  {
    id: 3,
    type: "property",
    title: "6-Unit Mixed Use",
    price: 480000,
    metric: "7.5%",
    metricLabel: "Cap Rate",
    city: "Worcester, MA",
    daysListed: 1,
    sourceUrl: "https://www.loopnet.com/listing/quincy-ma/2",
  },
  {
    id: 4,
    type: "business",
    title: "Auto Repair Shop",
    price: 250000,
    metric: "3.1x",
    metricLabel: "Multiple",
    city: "Fall River, MA",
    daysListed: 8,
    sourceUrl: "https://www.bizbuysell.com/listing/hvac-company",
  },
  {
    id: 5,
    type: "property",
    title: "8-Unit Apartment",
    price: 550000,
    metric: "6.9%",
    metricLabel: "Cap Rate",
    city: "Lynn, MA",
    daysListed: 12,
    sourceUrl: "https://www.loopnet.com/listing/worcester-ma/3",
  },
  {
    id: 6,
    type: "business",
    title: "Pizza Restaurant",
    price: 125000,
    metric: "2.2x",
    metricLabel: "Multiple",
    city: "Lowell, MA",
    daysListed: 2,
    sourceUrl: "https://www.bizbuysell.com/listing/auto-detail",
  },
];

export interface WatchlistMover {
  symbol: string;
  name: string;
  price: number;
  changePct: number;
}

export const watchlistMovers: WatchlistMover[] = [
  { symbol: "AAPL", name: "Apple", price: 178.72, changePct: 2.31 },
  { symbol: "O", name: "Realty Income", price: 54.38, changePct: 1.14 },
  { symbol: "MSFT", name: "Microsoft", price: 422.86, changePct: -0.52 },
  { symbol: "SCHD", name: "Schwab Dividend", price: 78.94, changePct: 0.87 },
  { symbol: "VNQ", name: "Vanguard REIT", price: 82.13, changePct: -1.23 },
];

// ── Tax Delinquent Properties ──────────────────────────────────────────

export interface TaxDelinquentProperty {
  id: number;
  address: string;
  city: string;
  state: string;
  zip: string;
  ownerName: string;
  propertyType: 'single_family' | 'multi_family' | 'condo' | 'commercial' | 'land';
  assessedValue: number;
  estimatedMarketValue: number;
  totalTaxOwed: number;
  yearsDelinquent: number;
  taxTitleDate: string | null;
  status: 'tax_lien' | 'tax_title' | 'in_redemption' | 'foreclosure_pending';
  lastPaymentDate: string | null;
  lotSizeSqft: number | null;
  yearBuilt: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  units: number | null;
  source: string;
  sourceUrl: string | null;
  notes: string;
  addedAt: string;
  skipTrace?: {
    phones: { number: string; type: string }[];
    emails: string[];
    mailingAddress: string | null;
  } | null;
  skipTraceLoading?: boolean;
}

export const taxDelinquentProperties: TaxDelinquentProperty[] = [
  {
    id: 1,
    address: "47 Waverly Ave",
    city: "Newton",
    state: "MA",
    zip: "02458",
    ownerName: "Steven & Linda Park",
    propertyType: "single_family",
    assessedValue: 1350000,
    estimatedMarketValue: 1620000,
    totalTaxOwed: 142500,
    yearsDelinquent: 8,
    taxTitleDate: "2020-03-15",
    status: "tax_title",
    lastPaymentDate: "2018-01-12",
    lotSizeSqft: 11200,
    yearBuilt: 1952,
    bedrooms: 4,
    bathrooms: 2.5,
    units: null,
    source: "Newton Tax Collector",
    sourceUrl: "https://www.newtonma.gov/government/finance/tax-collector",
    notes: "Owners relocated overseas per mail returns.",
    addedAt: "2025-12-01",
  },
  {
    id: 2,
    address: "18 Centre St",
    city: "Dover",
    state: "MA",
    zip: "02030",
    ownerName: "Estate of Margaret Thorne",
    propertyType: "single_family",
    assessedValue: 2150000,
    estimatedMarketValue: 2650000,
    totalTaxOwed: 198400,
    yearsDelinquent: 10,
    taxTitleDate: "2018-06-20",
    status: "foreclosure_pending",
    lastPaymentDate: "2016-04-30",
    lotSizeSqft: 87120,
    yearBuilt: 1928,
    bedrooms: 6,
    bathrooms: 4.5,
    units: null,
    source: "Dover Tax Collector",
    sourceUrl: "https://www.doverma.org/tax-collector",
    notes: "2-acre estate. Heirs in dispute. Probate open since 2017.",
    addedAt: "2025-11-15",
  },
  {
    id: 3,
    address: "312 Washington St",
    city: "Wellesley",
    state: "MA",
    zip: "02481",
    ownerName: "Robert & Anne Kimball",
    propertyType: "single_family",
    assessedValue: 1580000,
    estimatedMarketValue: 1890000,
    totalTaxOwed: 118900,
    yearsDelinquent: 7,
    taxTitleDate: "2021-01-10",
    status: "tax_title",
    lastPaymentDate: "2019-06-15",
    lotSizeSqft: 14500,
    yearBuilt: 1965,
    bedrooms: 5,
    bathrooms: 3,
    units: null,
    source: "Wellesley Tax Collector",
    sourceUrl: "https://www.wellesleyma.gov/tax-collector",
    notes: "",
    addedAt: "2025-12-10",
  },
  {
    id: 4,
    address: "85 Highland St",
    city: "Weston",
    state: "MA",
    zip: "02493",
    ownerName: "Chen Family Trust",
    propertyType: "single_family",
    assessedValue: 2850000,
    estimatedMarketValue: 3400000,
    totalTaxOwed: 285000,
    yearsDelinquent: 8,
    taxTitleDate: "2020-09-05",
    status: "tax_title",
    lastPaymentDate: "2018-03-20",
    lotSizeSqft: 65340,
    yearBuilt: 1935,
    bedrooms: 7,
    bathrooms: 5,
    units: null,
    source: "Weston Tax Collector",
    sourceUrl: "https://www.weston.org/tax-collector",
    notes: "1.5-acre lot. Owner possibly deceased. Title search needed.",
    addedAt: "2025-11-28",
  },
  {
    id: 5,
    address: "140 Harvard St",
    city: "Brookline",
    state: "MA",
    zip: "02446",
    ownerName: "Dimitri Papadopoulos",
    propertyType: "multi_family",
    assessedValue: 1820000,
    estimatedMarketValue: 2150000,
    totalTaxOwed: 156200,
    yearsDelinquent: 6,
    taxTitleDate: "2022-02-14",
    status: "tax_lien",
    lastPaymentDate: "2020-05-10",
    lotSizeSqft: 6200,
    yearBuilt: 1912,
    bedrooms: 8,
    bathrooms: 4,
    units: 3,
    source: "Brookline Tax Collector",
    sourceUrl: "https://www.brooklinema.gov/tax-collector",
    notes: "3-unit Victorian. One unit occupied, two vacant.",
    addedAt: "2025-12-05",
  },
  {
    id: 6,
    address: "22 Dedham St",
    city: "Dover",
    state: "MA",
    zip: "02030",
    ownerName: "Whitfield Holdings LLC",
    propertyType: "land",
    assessedValue: 980000,
    estimatedMarketValue: 1250000,
    totalTaxOwed: 108500,
    yearsDelinquent: 12,
    taxTitleDate: "2016-11-30",
    status: "foreclosure_pending",
    lastPaymentDate: "2014-09-01",
    lotSizeSqft: 130680,
    yearBuilt: null,
    bedrooms: null,
    bathrooms: null,
    units: null,
    source: "Dover Tax Collector",
    sourceUrl: "https://www.doverma.org/tax-collector",
    notes: "3-acre parcel. Subdividable. Perc test passed 2013.",
    addedAt: "2025-10-20",
  },
  {
    id: 7,
    address: "567 Boylston St",
    city: "Brookline",
    state: "MA",
    zip: "02445",
    ownerName: "Gloria M. Sullivan",
    propertyType: "single_family",
    assessedValue: 1420000,
    estimatedMarketValue: 1680000,
    totalTaxOwed: 98400,
    yearsDelinquent: 7,
    taxTitleDate: "2021-04-22",
    status: "in_redemption",
    lastPaymentDate: "2019-11-30",
    lotSizeSqft: 7800,
    yearBuilt: 1940,
    bedrooms: 4,
    bathrooms: 2.5,
    units: null,
    source: "Brookline Tax Collector",
    sourceUrl: "https://www.brooklinema.gov/tax-collector",
    notes: "Owner in assisted living. Family attempting payment plan.",
    addedAt: "2025-11-10",
  },
  {
    id: 8,
    address: "44 Church St",
    city: "Wellesley",
    state: "MA",
    zip: "02482",
    ownerName: "Michael & Sandra Reeves",
    propertyType: "single_family",
    assessedValue: 1950000,
    estimatedMarketValue: 2380000,
    totalTaxOwed: 175200,
    yearsDelinquent: 9,
    taxTitleDate: "2019-07-18",
    status: "tax_title",
    lastPaymentDate: "2017-02-28",
    lotSizeSqft: 18200,
    yearBuilt: 1922,
    bedrooms: 5,
    bathrooms: 3.5,
    units: null,
    source: "Wellesley Tax Collector",
    sourceUrl: "https://www.wellesleyma.gov/tax-collector",
    notes: "Near Wellesley College. Significant deferred maintenance.",
    addedAt: "2025-12-08",
  },
  {
    id: 9,
    address: "91 Walnut St",
    city: "Newton",
    state: "MA",
    zip: "02460",
    ownerName: "Patricia Liu",
    propertyType: "condo",
    assessedValue: 725000,
    estimatedMarketValue: 850000,
    totalTaxOwed: 62100,
    yearsDelinquent: 5,
    taxTitleDate: null,
    status: "tax_lien",
    lastPaymentDate: "2021-08-15",
    lotSizeSqft: null,
    yearBuilt: 1988,
    bedrooms: 2,
    bathrooms: 2,
    units: null,
    source: "Newton Tax Collector",
    sourceUrl: "https://www.newtonma.gov/government/finance/tax-collector",
    notes: "Condo fees also in arrears per HOA.",
    addedAt: "2025-12-12",
  },
  {
    id: 10,
    address: "203 Chestnut Hill Rd",
    city: "Newton",
    state: "MA",
    zip: "02467",
    ownerName: "Estate of Harold Stein",
    propertyType: "single_family",
    assessedValue: 2450000,
    estimatedMarketValue: 2980000,
    totalTaxOwed: 215600,
    yearsDelinquent: 6,
    taxTitleDate: "2022-05-01",
    status: "tax_title",
    lastPaymentDate: "2020-01-20",
    lotSizeSqft: 22500,
    yearBuilt: 1942,
    bedrooms: 6,
    bathrooms: 4.5,
    units: null,
    source: "Newton Tax Collector",
    sourceUrl: "https://www.newtonma.gov/government/finance/tax-collector",
    notes: "Chestnut Hill area. Probate pending. High-value.",
    addedAt: "2025-11-22",
  },
  {
    id: 11,
    address: "15 Pine Ridge Rd",
    city: "Weston",
    state: "MA",
    zip: "02493",
    ownerName: "Anthony Marchetti",
    propertyType: "land",
    assessedValue: 750000,
    estimatedMarketValue: 950000,
    totalTaxOwed: 82400,
    yearsDelinquent: 9,
    taxTitleDate: "2019-12-01",
    status: "tax_title",
    lastPaymentDate: "2017-06-10",
    lotSizeSqft: 87120,
    yearBuilt: null,
    bedrooms: null,
    bathrooms: null,
    units: null,
    source: "Weston Tax Collector",
    sourceUrl: "https://www.weston.org/tax-collector",
    notes: "2-acre lot. Town water available. Zoned RS-A.",
    addedAt: "2025-12-01",
  },
  {
    id: 12,
    address: "78 Beacon St",
    city: "Brookline",
    state: "MA",
    zip: "02446",
    ownerName: "Kevin O'Malley",
    propertyType: "multi_family",
    assessedValue: 2200000,
    estimatedMarketValue: 2650000,
    totalTaxOwed: 225700,
    yearsDelinquent: 10,
    taxTitleDate: "2018-08-15",
    status: "foreclosure_pending",
    lastPaymentDate: "2016-12-01",
    lotSizeSqft: 8400,
    yearBuilt: 1905,
    bedrooms: 10,
    bathrooms: 5,
    units: 4,
    source: "Brookline Tax Collector",
    sourceUrl: "https://www.brooklinema.gov/tax-collector",
    notes: "4-unit brownstone. City code violations on file.",
    addedAt: "2025-10-15",
  },
  {
    id: 13,
    address: "330 Grove St",
    city: "Wellesley",
    state: "MA",
    zip: "02482",
    ownerName: "Rosa Chen Estate",
    propertyType: "single_family",
    assessedValue: 1680000,
    estimatedMarketValue: 2050000,
    totalTaxOwed: 168100,
    yearsDelinquent: 11,
    taxTitleDate: "2017-03-20",
    status: "foreclosure_pending",
    lastPaymentDate: "2015-07-15",
    lotSizeSqft: 15600,
    yearBuilt: 1918,
    bedrooms: 5,
    bathrooms: 3,
    units: null,
    source: "Wellesley Tax Collector",
    sourceUrl: "https://www.wellesleyma.gov/tax-collector",
    notes: "Probate case open. 3 heirs identified across states.",
    addedAt: "2025-11-05",
  },
  {
    id: 14,
    address: "8 Farm St",
    city: "Dover",
    state: "MA",
    zip: "02030",
    ownerName: "Samuel & Jean Harrington",
    propertyType: "single_family",
    assessedValue: 1870000,
    estimatedMarketValue: 2300000,
    totalTaxOwed: 135800,
    yearsDelinquent: 6,
    taxTitleDate: "2022-01-10",
    status: "tax_lien",
    lastPaymentDate: "2020-03-15",
    lotSizeSqft: 43560,
    yearBuilt: 1955,
    bedrooms: 4,
    bathrooms: 3,
    units: null,
    source: "Dover Tax Collector",
    sourceUrl: "https://www.doverma.org/tax-collector",
    notes: "1-acre lot. Owners elderly, no mortgage on file.",
    addedAt: "2025-12-15",
  },
  {
    id: 15,
    address: "445 Washington St",
    city: "Brookline",
    state: "MA",
    zip: "02445",
    ownerName: "Garcia Properties Inc",
    propertyType: "commercial",
    assessedValue: 3200000,
    estimatedMarketValue: 3850000,
    totalTaxOwed: 318500,
    yearsDelinquent: 11,
    taxTitleDate: "2017-09-01",
    status: "foreclosure_pending",
    lastPaymentDate: "2015-04-20",
    lotSizeSqft: 9800,
    yearBuilt: 1920,
    bedrooms: null,
    bathrooms: null,
    units: null,
    source: "Brookline Tax Collector",
    sourceUrl: "https://www.brooklinema.gov/tax-collector",
    notes: "Mixed-use. Ground floor retail, 4 luxury apts above. Coolidge Corner area.",
    addedAt: "2025-10-30",
  },
  {
    id: 16,
    address: "62 Hundreds Rd",
    city: "Wellesley",
    state: "MA",
    zip: "02481",
    ownerName: "Tran Family Trust",
    propertyType: "single_family",
    assessedValue: 1720000,
    estimatedMarketValue: 2100000,
    totalTaxOwed: 126800,
    yearsDelinquent: 7,
    taxTitleDate: "2021-06-15",
    status: "tax_title",
    lastPaymentDate: "2019-09-01",
    lotSizeSqft: 16800,
    yearBuilt: 1932,
    bedrooms: 5,
    bathrooms: 3.5,
    units: null,
    source: "Wellesley Tax Collector",
    sourceUrl: "https://www.wellesleyma.gov/tax-collector",
    notes: "Dana Hall area. Trust beneficiaries unreachable.",
    addedAt: "2025-12-03",
  },
  {
    id: 17,
    address: "190 Ash St",
    city: "Weston",
    state: "MA",
    zip: "02493",
    ownerName: "David & Ellen Kraft",
    propertyType: "single_family",
    assessedValue: 3100000,
    estimatedMarketValue: 3750000,
    totalTaxOwed: 342000,
    yearsDelinquent: 12,
    taxTitleDate: "2016-04-10",
    status: "foreclosure_pending",
    lastPaymentDate: "2014-11-30",
    lotSizeSqft: 108900,
    yearBuilt: 1910,
    bedrooms: 8,
    bathrooms: 6,
    units: null,
    source: "Weston Tax Collector",
    sourceUrl: "https://www.weston.org/tax-collector",
    notes: "2.5-acre estate. Historic home. Both owners deceased.",
    addedAt: "2025-11-18",
  },
  {
    id: 18,
    address: "55 Oak Hill Ave",
    city: "Newton",
    state: "MA",
    zip: "02460",
    ownerName: "Yolanda Freeman",
    propertyType: "single_family",
    assessedValue: 1180000,
    estimatedMarketValue: 1420000,
    totalTaxOwed: 94200,
    yearsDelinquent: 7,
    taxTitleDate: "2021-03-01",
    status: "in_redemption",
    lastPaymentDate: "2019-10-15",
    lotSizeSqft: 9200,
    yearBuilt: 1960,
    bedrooms: 4,
    bathrooms: 2.5,
    units: null,
    source: "Newton Tax Collector",
    sourceUrl: "https://www.newtonma.gov/government/finance/tax-collector",
    notes: "Owner attempting payment plan. May redeem within 6mo.",
    addedAt: "2025-12-14",
  },
  {
    id: 19,
    address: "28 Clyde St",
    city: "Brookline",
    state: "MA",
    zip: "02467",
    ownerName: "Estate of Ruth Goldberg",
    propertyType: "condo",
    assessedValue: 890000,
    estimatedMarketValue: 1050000,
    totalTaxOwed: 78700,
    yearsDelinquent: 5,
    taxTitleDate: null,
    status: "tax_lien",
    lastPaymentDate: "2021-06-30",
    lotSizeSqft: null,
    yearBuilt: 1975,
    bedrooms: 3,
    bathrooms: 2,
    units: null,
    source: "Brookline Tax Collector",
    sourceUrl: "https://www.brooklinema.gov/tax-collector",
    notes: "Chestnut Hill condo. Probate pending.",
    addedAt: "2025-12-16",
  },
  {
    id: 20,
    address: "77 Glen Rd",
    city: "Weston",
    state: "MA",
    zip: "02493",
    ownerName: "Frank Bellingham III",
    propertyType: "single_family",
    assessedValue: 2680000,
    estimatedMarketValue: 3200000,
    totalTaxOwed: 195800,
    yearsDelinquent: 5,
    taxTitleDate: null,
    status: "tax_lien",
    lastPaymentDate: "2021-04-10",
    lotSizeSqft: 52272,
    yearBuilt: 1985,
    bedrooms: 5,
    bathrooms: 4,
    units: null,
    source: "Weston Tax Collector",
    sourceUrl: "https://www.weston.org/tax-collector",
    notes: "1.2-acre lot. Pool and tennis court. Owner in bankruptcy.",
    addedAt: "2025-12-18",
  },
];

export interface AlertItem {
  id: number;
  type: "new_listing" | "rate_drop" | "price_cut";
  message: string;
  time: string;
}

export const recentAlerts: AlertItem[] = [
  {
    id: 1,
    type: "new_listing",
    message: "New listing: Auto shop $250K in Fall River",
    time: "12m ago",
  },
  {
    id: 2,
    type: "rate_drop",
    message: "Rate drop: First Credit Union 30yr now 6.25%",
    time: "2h ago",
  },
  {
    id: 3,
    type: "price_cut",
    message: "Price cut: 8-unit MF reduced to $550K",
    time: "5h ago",
  },
  {
    id: 4,
    type: "new_listing",
    message: "New listing: Coin laundromat $185K in Quincy",
    time: "8h ago",
  },
];
