export interface RentRollEntry {
  unit: string;
  rent: number;
  occupied: boolean;
}

export interface REListing {
  id: number;
  address: string;
  city: string;
  state: string;
  zip: string;
  propertyType: 'multifamily' | 'mixed_use' | 'retail' | 'office' | 'industrial' | 'land';
  askingPrice: number;
  units: number | null;
  sqft: number | null;
  lotSize: number | null;
  yearBuilt: number | null;
  occupancyPct: number | null;
  reportedNoi: number | null;
  estimatedNoi: number | null;
  reportedCapRate: number | null;
  estimatedCapRate: number | null;
  grossRent: number | null;
  taxes: number | null;
  insurance: number | null;
  hoa: number | null;
  pricePerUnit: number | null;
  pricePerSqft: number | null;
  brokerName: string | null;
  brokerCompany: string | null;
  brokerPhone: string | null;
  sourcePlatform: string;
  sourceUrl: string | null;
  daysListed: number;
  status: 'active' | 'under_contract' | 'sold' | 'off_market';
  notes: string;
  rentRoll: RentRollEntry[] | null;
}

export const propertyTypes = [
  { value: 'all', label: 'All Types' },
  { value: 'multifamily', label: 'Multifamily' },
  { value: 'mixed_use', label: 'Mixed-Use' },
  { value: 'retail', label: 'Retail' },
  { value: 'office', label: 'Office' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'land', label: 'Land' },
] as const;

export const reStatuses = [
  { value: 'all', label: 'All' },
  { value: 'active', label: 'Active' },
  { value: 'under_contract', label: 'Under Contract' },
  { value: 'sold', label: 'Sold' },
  { value: 'off_market', label: 'Off Market' },
] as const;

export const reSortOptions = [
  { value: 'capRate', label: 'Cap Rate' },
  { value: 'price', label: 'Price' },
  { value: 'pricePerUnit', label: 'Price/Unit' },
  { value: 'pricePerSqft', label: 'Price/SqFt' },
  { value: 'units', label: 'Units' },
  { value: 'daysListed', label: 'Days Listed' },
] as const;

export function getCapRate(listing: REListing): number | null {
  return listing.reportedCapRate ?? listing.estimatedCapRate ?? null;
}

export function getNoi(listing: REListing): number | null {
  return listing.reportedNoi ?? listing.estimatedNoi ?? null;
}

export function isEstimatedCapRate(listing: REListing): boolean {
  return listing.reportedCapRate == null && listing.estimatedCapRate != null;
}

export function isEstimatedNoi(listing: REListing): boolean {
  return listing.reportedNoi == null && listing.estimatedNoi != null;
}

export const propertyTypeLabels: Record<string, string> = {
  multifamily: 'Multifamily',
  mixed_use: 'Mixed-Use',
  retail: 'Retail',
  office: 'Office',
  industrial: 'Industrial',
  land: 'Land',
};

export const mockREListings: REListing[] = [
  {
    id: 1,
    address: "47 Elm Street",
    city: "Worcester",
    state: "MA",
    zip: "01609",
    propertyType: "multifamily",
    askingPrice: 1250000,
    units: 12,
    sqft: 9600,
    lotSize: 0.45,
    yearBuilt: 1962,
    occupancyPct: 92,
    reportedNoi: 137500,
    estimatedNoi: null,
    reportedCapRate: 11.0,
    estimatedCapRate: null,
    grossRent: 194400,
    taxes: 18200,
    insurance: 8400,
    hoa: null,
    pricePerUnit: 104167,
    pricePerSqft: 130,
    brokerName: "Mike Delaney",
    brokerCompany: "NAI Glickman Kovago",
    brokerPhone: "(508) 752-9100",
    sourcePlatform: "LoopNet",
    sourceUrl: "https://loopnet.com/listing/47-elm-worcester",
    daysListed: 14,
    status: "active",
    notes: "",
    rentRoll: [
      { unit: "1A", rent: 1350, occupied: true },
      { unit: "1B", rent: 1350, occupied: true },
      { unit: "2A", rent: 1400, occupied: true },
      { unit: "2B", rent: 1400, occupied: true },
      { unit: "3A", rent: 1500, occupied: true },
      { unit: "3B", rent: 1500, occupied: false },
      { unit: "4A", rent: 1650, occupied: true },
      { unit: "4B", rent: 1650, occupied: true },
      { unit: "5A", rent: 1700, occupied: true },
      { unit: "5B", rent: 1700, occupied: true },
      { unit: "6A", rent: 1600, occupied: true },
      { unit: "6B", rent: 1600, occupied: true },
    ],
  },
  {
    id: 2,
    address: "312 Broadway",
    city: "Lowell",
    state: "MA",
    zip: "01852",
    propertyType: "mixed_use",
    askingPrice: 875000,
    units: 6,
    sqft: 5400,
    lotSize: 0.18,
    yearBuilt: 1945,
    occupancyPct: 100,
    reportedNoi: null,
    estimatedNoi: 87500,
    reportedCapRate: null,
    estimatedCapRate: 10.0,
    grossRent: 126000,
    taxes: 12800,
    insurance: 5200,
    hoa: null,
    pricePerUnit: 145833,
    pricePerSqft: 162,
    brokerName: "Janet Sullivan",
    brokerCompany: "Coldwell Banker Commercial",
    brokerPhone: "(978) 458-2100",
    sourcePlatform: "Crexi",
    sourceUrl: "https://crexi.com/properties/312-broadway-lowell",
    daysListed: 38,
    status: "active",
    notes: "",
    rentRoll: [
      { unit: "Store", rent: 3500, occupied: true },
      { unit: "2A", rent: 1600, occupied: true },
      { unit: "2B", rent: 1600, occupied: true },
      { unit: "3A", rent: 1500, occupied: true },
      { unit: "3B", rent: 1500, occupied: true },
      { unit: "3C", rent: 800, occupied: true },
    ],
  },
  {
    id: 3,
    address: "89 Federal Street",
    city: "Brockton",
    state: "MA",
    zip: "02301",
    propertyType: "multifamily",
    askingPrice: 685000,
    units: 8,
    sqft: 6200,
    lotSize: 0.22,
    yearBuilt: 1958,
    occupancyPct: 88,
    reportedNoi: 63000,
    estimatedNoi: null,
    reportedCapRate: 9.2,
    estimatedCapRate: null,
    grossRent: 102000,
    taxes: 11400,
    insurance: 6100,
    hoa: null,
    pricePerUnit: 85625,
    pricePerSqft: 110,
    brokerName: "Carlos Mendes",
    brokerCompany: "Keller Williams",
    brokerPhone: "(508) 583-4200",
    sourcePlatform: "LoopNet",
    sourceUrl: null,
    daysListed: 67,
    status: "active",
    notes: "Roof replaced 2021. Two vacancies in basement units.",
    rentRoll: [
      { unit: "1", rent: 1200, occupied: true },
      { unit: "2", rent: 1200, occupied: true },
      { unit: "3", rent: 1300, occupied: true },
      { unit: "4", rent: 1300, occupied: true },
      { unit: "5", rent: 1400, occupied: true },
      { unit: "6", rent: 1400, occupied: true },
      { unit: "B1", rent: 900, occupied: false },
      { unit: "B2", rent: 800, occupied: false },
    ],
  },
  {
    id: 4,
    address: "1540 Commonwealth Ave",
    city: "Brighton",
    state: "MA",
    zip: "02135",
    propertyType: "multifamily",
    askingPrice: 3200000,
    units: 18,
    sqft: 16200,
    lotSize: 0.35,
    yearBuilt: 1928,
    occupancyPct: 95,
    reportedNoi: 272000,
    estimatedNoi: null,
    reportedCapRate: 8.5,
    estimatedCapRate: null,
    grossRent: 388800,
    taxes: 42000,
    insurance: 18500,
    hoa: null,
    pricePerUnit: 177778,
    pricePerSqft: 198,
    brokerName: "Tom Brennan",
    brokerCompany: "Marcus & Millichap",
    brokerPhone: "(617) onal-5000",
    sourcePlatform: "Broker Direct",
    sourceUrl: null,
    daysListed: 5,
    status: "active",
    notes: "",
    rentRoll: null,
  },
  {
    id: 5,
    address: "22 Waverly Street",
    city: "Framingham",
    state: "MA",
    zip: "01702",
    propertyType: "multifamily",
    askingPrice: 2100000,
    units: 16,
    sqft: 12800,
    lotSize: 0.52,
    yearBuilt: 1971,
    occupancyPct: 94,
    reportedNoi: null,
    estimatedNoi: 178500,
    reportedCapRate: null,
    estimatedCapRate: 8.5,
    grossRent: 264000,
    taxes: 28500,
    insurance: 14200,
    hoa: null,
    pricePerUnit: 131250,
    pricePerSqft: 164,
    brokerName: "David Chen",
    brokerCompany: "Horvath & Tremblay",
    brokerPhone: "(508) 875-3400",
    sourcePlatform: "Crexi",
    sourceUrl: "https://crexi.com/properties/22-waverly-framingham",
    daysListed: 22,
    status: "active",
    notes: "",
    rentRoll: null,
  },
  {
    id: 6,
    address: "455 Broad Street",
    city: "Providence",
    state: "RI",
    zip: "02907",
    propertyType: "multifamily",
    askingPrice: 1750000,
    units: 20,
    sqft: 15000,
    lotSize: 0.60,
    yearBuilt: 1955,
    occupancyPct: 90,
    reportedNoi: 148750,
    estimatedNoi: null,
    reportedCapRate: 8.5,
    estimatedCapRate: null,
    grossRent: 228000,
    taxes: 22400,
    insurance: 12800,
    hoa: null,
    pricePerUnit: 87500,
    pricePerSqft: 117,
    brokerName: "Anthony Ricci",
    brokerCompany: "Sweeney Real Estate",
    brokerPhone: "(401) 421-8888",
    sourcePlatform: "LoopNet",
    sourceUrl: "https://loopnet.com/listing/455-broad-providence",
    daysListed: 45,
    status: "active",
    notes: "",
    rentRoll: null,
  },
  {
    id: 7,
    address: "78 Central Street",
    city: "Somerville",
    state: "MA",
    zip: "02143",
    propertyType: "mixed_use",
    askingPrice: 2850000,
    units: 8,
    sqft: 7200,
    lotSize: 0.15,
    yearBuilt: 1910,
    occupancyPct: 100,
    reportedNoi: null,
    estimatedNoi: 228000,
    reportedCapRate: null,
    estimatedCapRate: 8.0,
    grossRent: 336000,
    taxes: 38500,
    insurance: 12400,
    hoa: null,
    pricePerUnit: 356250,
    pricePerSqft: 396,
    brokerName: "Sarah Kim",
    brokerCompany: "Compass Commercial",
    brokerPhone: "(617) 625-7800",
    sourcePlatform: "Broker Direct",
    sourceUrl: null,
    daysListed: 3,
    status: "active",
    notes: "Restaurant on ground floor — long-term NNN lease through 2031.",
    rentRoll: [
      { unit: "Restaurant", rent: 8500, occupied: true },
      { unit: "2A", rent: 2800, occupied: true },
      { unit: "2B", rent: 2800, occupied: true },
      { unit: "3A", rent: 2600, occupied: true },
      { unit: "3B", rent: 2600, occupied: true },
      { unit: "4A", rent: 2500, occupied: true },
      { unit: "4B", rent: 2500, occupied: true },
      { unit: "4C", rent: 2700, occupied: true },
    ],
  },
  {
    id: 8,
    address: "190 Main Street",
    city: "Quincy",
    state: "MA",
    zip: "02169",
    propertyType: "retail",
    askingPrice: 1450000,
    units: 3,
    sqft: 8500,
    lotSize: 0.30,
    yearBuilt: 1985,
    occupancyPct: 67,
    reportedNoi: 108750,
    estimatedNoi: null,
    reportedCapRate: 7.5,
    estimatedCapRate: null,
    grossRent: 170000,
    taxes: 19800,
    insurance: 7200,
    hoa: null,
    pricePerUnit: 483333,
    pricePerSqft: 171,
    brokerName: "Greg Papadopoulos",
    brokerCompany: "CBRE New England",
    brokerPhone: "(617) 912-7000",
    sourcePlatform: "LoopNet",
    sourceUrl: "https://loopnet.com/listing/190-main-quincy",
    daysListed: 92,
    status: "active",
    notes: "One vacancy — former dry cleaner space.",
    rentRoll: [
      { unit: "A", rent: 6500, occupied: true },
      { unit: "B", rent: 4800, occupied: true },
      { unit: "C", rent: 2900, occupied: false },
    ],
  },
  {
    id: 9,
    address: "33 Exchange Street",
    city: "Cambridge",
    state: "MA",
    zip: "02141",
    propertyType: "office",
    askingPrice: 5400000,
    units: null,
    sqft: 22000,
    lotSize: 0.40,
    yearBuilt: 1999,
    occupancyPct: 78,
    reportedNoi: 378000,
    estimatedNoi: null,
    reportedCapRate: 7.0,
    estimatedCapRate: null,
    grossRent: 550000,
    taxes: 68000,
    insurance: 22000,
    hoa: null,
    pricePerUnit: null,
    pricePerSqft: 245,
    brokerName: "William Frost",
    brokerCompany: "JLL Boston",
    brokerPhone: "(617) 316-6000",
    sourcePlatform: "Crexi",
    sourceUrl: "https://crexi.com/properties/33-exchange-cambridge",
    daysListed: 120,
    status: "active",
    notes: "Biotech tenant vacated one floor. Below market rents on remaining.",
    rentRoll: null,
  },
  {
    id: 10,
    address: "812 Chelmsford Street",
    city: "Lowell",
    state: "MA",
    zip: "01851",
    propertyType: "industrial",
    askingPrice: 975000,
    units: null,
    sqft: 14000,
    lotSize: 1.2,
    yearBuilt: 1978,
    occupancyPct: 100,
    reportedNoi: null,
    estimatedNoi: 92625,
    reportedCapRate: null,
    estimatedCapRate: 9.5,
    grossRent: 126000,
    taxes: 14200,
    insurance: 8400,
    hoa: null,
    pricePerUnit: null,
    pricePerSqft: 70,
    brokerName: "Paul Thibodeau",
    brokerCompany: "Nordlund Associates",
    brokerPhone: "(978) 459-2200",
    sourcePlatform: "LoopNet",
    sourceUrl: null,
    daysListed: 30,
    status: "active",
    notes: "Single tenant NNN — 4 years remaining on lease.",
    rentRoll: null,
  },
  {
    id: 11,
    address: "265 Grafton Street",
    city: "Worcester",
    state: "MA",
    zip: "01604",
    propertyType: "multifamily",
    askingPrice: 520000,
    units: 6,
    sqft: 4800,
    lotSize: 0.18,
    yearBuilt: 1940,
    occupancyPct: 83,
    reportedNoi: null,
    estimatedNoi: 46800,
    reportedCapRate: null,
    estimatedCapRate: 9.0,
    grossRent: 79200,
    taxes: 8900,
    insurance: 4800,
    hoa: null,
    pricePerUnit: 86667,
    pricePerSqft: 108,
    brokerName: "Linda Petrosky",
    brokerCompany: "RE/MAX Vision",
    brokerPhone: "(508) 791-7700",
    sourcePlatform: "Manual",
    sourceUrl: null,
    daysListed: 55,
    status: "active",
    notes: "Needs exterior work. One unit gut-renovated in 2023.",
    rentRoll: [
      { unit: "1", rent: 1100, occupied: true },
      { unit: "2", rent: 1100, occupied: true },
      { unit: "3", rent: 1200, occupied: true },
      { unit: "4", rent: 1200, occupied: true },
      { unit: "5", rent: 1300, occupied: false },
      { unit: "6", rent: 700, occupied: true },
    ],
  },
  {
    id: 12,
    address: "15 Hancock Street",
    city: "Brookline",
    state: "MA",
    zip: "02446",
    propertyType: "multifamily",
    askingPrice: 4500000,
    units: 10,
    sqft: 11000,
    lotSize: 0.28,
    yearBuilt: 1920,
    occupancyPct: 100,
    reportedNoi: 315000,
    estimatedNoi: null,
    reportedCapRate: 7.0,
    estimatedCapRate: null,
    grossRent: 450000,
    taxes: 52000,
    insurance: 16500,
    hoa: null,
    pricePerUnit: 450000,
    pricePerSqft: 409,
    brokerName: "Elizabeth Moody",
    brokerCompany: "Hammond Residential",
    brokerPhone: "(617) 731-4644",
    sourcePlatform: "Broker Direct",
    sourceUrl: null,
    daysListed: 8,
    status: "active",
    notes: "Premium Coolidge Corner location. All units renovated 2019-2022.",
    rentRoll: null,
  },
  {
    id: 13,
    address: "900 Warren Avenue",
    city: "Brockton",
    state: "MA",
    zip: "02301",
    propertyType: "multifamily",
    askingPrice: 1650000,
    units: 24,
    sqft: 18000,
    lotSize: 0.85,
    yearBuilt: 1968,
    occupancyPct: 79,
    reportedNoi: 148500,
    estimatedNoi: null,
    reportedCapRate: 9.0,
    estimatedCapRate: null,
    grossRent: 259200,
    taxes: 24800,
    insurance: 16200,
    hoa: null,
    pricePerUnit: 68750,
    pricePerSqft: 92,
    brokerName: "Carlos Mendes",
    brokerCompany: "Keller Williams",
    brokerPhone: "(508) 583-4200",
    sourcePlatform: "LoopNet",
    sourceUrl: "https://loopnet.com/listing/900-warren-brockton",
    daysListed: 78,
    status: "active",
    notes: "Value-add opportunity — 5 vacant units need renovation.",
    rentRoll: null,
  },
  {
    id: 14,
    address: "405 Weir Street",
    city: "Taunton",
    state: "MA",
    zip: "02780",
    propertyType: "mixed_use",
    askingPrice: 395000,
    units: 4,
    sqft: 3600,
    lotSize: 0.12,
    yearBuilt: 1952,
    occupancyPct: 100,
    reportedNoi: null,
    estimatedNoi: 39500,
    reportedCapRate: null,
    estimatedCapRate: 10.0,
    grossRent: 62400,
    taxes: 6800,
    insurance: 3200,
    hoa: null,
    pricePerUnit: 98750,
    pricePerSqft: 110,
    brokerName: "Dennis Amaral",
    brokerCompany: "Century 21 Taunton",
    brokerPhone: "(508) 824-6100",
    sourcePlatform: "Crexi",
    sourceUrl: null,
    daysListed: 42,
    status: "active",
    notes: "Barber shop ground floor. All apartments rented.",
    rentRoll: [
      { unit: "Store", rent: 1200, occupied: true },
      { unit: "2A", rent: 1300, occupied: true },
      { unit: "2B", rent: 1300, occupied: true },
      { unit: "3", rent: 1400, occupied: true },
    ],
  },
  {
    id: 15,
    address: "2200 Main Street",
    city: "Springfield",
    state: "MA",
    zip: "01103",
    propertyType: "multifamily",
    askingPrice: 2800000,
    units: 40,
    sqft: 32000,
    lotSize: 1.5,
    yearBuilt: 1970,
    occupancyPct: 85,
    reportedNoi: 252000,
    estimatedNoi: null,
    reportedCapRate: 9.0,
    estimatedCapRate: null,
    grossRent: 384000,
    taxes: 38400,
    insurance: 28000,
    hoa: null,
    pricePerUnit: 70000,
    pricePerSqft: 88,
    brokerName: "Rick Fontaine",
    brokerCompany: "Berkshire Realty Group",
    brokerPhone: "(413) 781-5000",
    sourcePlatform: "LoopNet",
    sourceUrl: "https://loopnet.com/listing/2200-main-springfield",
    daysListed: 110,
    status: "active",
    notes: "Exterior renovated 2020. Some interior deferred maintenance.",
    rentRoll: null,
  },
  {
    id: 16,
    address: "58 Newton Street",
    city: "Newton",
    state: "MA",
    zip: "02458",
    propertyType: "multifamily",
    askingPrice: 7200000,
    units: 24,
    sqft: 22000,
    lotSize: 0.65,
    yearBuilt: 1987,
    occupancyPct: 96,
    reportedNoi: 396000,
    estimatedNoi: null,
    reportedCapRate: 5.5,
    estimatedCapRate: null,
    grossRent: 576000,
    taxes: 78000,
    insurance: 24500,
    hoa: null,
    pricePerUnit: 300000,
    pricePerSqft: 327,
    brokerName: "Rebecca Levy",
    brokerCompany: "Colliers Boston",
    brokerPhone: "(617) 330-8000",
    sourcePlatform: "Broker Direct",
    sourceUrl: null,
    daysListed: 15,
    status: "active",
    notes: "Class A suburban multifamily. Institutional-quality asset.",
    rentRoll: null,
  },
  {
    id: 17,
    address: "122 Canal Street",
    city: "Lawrence",
    state: "MA",
    zip: "01840",
    propertyType: "industrial",
    askingPrice: 1100000,
    units: null,
    sqft: 18000,
    lotSize: 0.95,
    yearBuilt: 1965,
    occupancyPct: 100,
    reportedNoi: 99000,
    estimatedNoi: null,
    reportedCapRate: 9.0,
    estimatedCapRate: null,
    grossRent: 144000,
    taxes: 16200,
    insurance: 9800,
    hoa: null,
    pricePerUnit: null,
    pricePerSqft: 61,
    brokerName: "Kevin O'Brien",
    brokerCompany: "O'Brien Commercial",
    brokerPhone: "(978) 794-1200",
    sourcePlatform: "Manual",
    sourceUrl: null,
    daysListed: 20,
    status: "under_contract",
    notes: "Distribution warehouse — two loading docks.",
    rentRoll: null,
  },
  {
    id: 18,
    address: "740 Purchase Street",
    city: "New Bedford",
    state: "MA",
    zip: "02740",
    propertyType: "multifamily",
    askingPrice: 980000,
    units: 14,
    sqft: 10500,
    lotSize: 0.38,
    yearBuilt: 1950,
    occupancyPct: 86,
    reportedNoi: null,
    estimatedNoi: 93100,
    reportedCapRate: null,
    estimatedCapRate: 9.5,
    grossRent: 151200,
    taxes: 15400,
    insurance: 9200,
    hoa: null,
    pricePerUnit: 70000,
    pricePerSqft: 93,
    brokerName: "Maria Santos",
    brokerCompany: "Re/Max Right Choice",
    brokerPhone: "(508) 999-3400",
    sourcePlatform: "Crexi",
    sourceUrl: null,
    daysListed: 63,
    status: "active",
    notes: "",
    rentRoll: null,
  },
  {
    id: 19,
    address: "85 Summer Street",
    city: "Haverhill",
    state: "MA",
    zip: "01830",
    propertyType: "retail",
    askingPrice: 625000,
    units: 2,
    sqft: 4200,
    lotSize: 0.15,
    yearBuilt: 1975,
    occupancyPct: 100,
    reportedNoi: 50000,
    estimatedNoi: null,
    reportedCapRate: 8.0,
    estimatedCapRate: null,
    grossRent: 72000,
    taxes: 8400,
    insurance: 3800,
    hoa: null,
    pricePerUnit: 312500,
    pricePerSqft: 149,
    brokerName: "Steve Kelleher",
    brokerCompany: "Kelleher & Associates",
    brokerPhone: "(978) 374-0800",
    sourcePlatform: "Manual",
    sourceUrl: null,
    daysListed: 18,
    status: "active",
    notes: "Pizza shop + convenience store. Both long-term tenants.",
    rentRoll: [
      { unit: "A", rent: 3500, occupied: true },
      { unit: "B", rent: 2500, occupied: true },
    ],
  },
  {
    id: 20,
    address: "1010 Reservoir Avenue",
    city: "Cranston",
    state: "RI",
    zip: "02910",
    propertyType: "land",
    askingPrice: 450000,
    units: null,
    sqft: null,
    lotSize: 2.1,
    yearBuilt: null,
    occupancyPct: null,
    reportedNoi: null,
    estimatedNoi: null,
    reportedCapRate: null,
    estimatedCapRate: null,
    grossRent: null,
    taxes: 4200,
    insurance: null,
    hoa: null,
    pricePerUnit: null,
    pricePerSqft: null,
    brokerName: "Anthony Ricci",
    brokerCompany: "Sweeney Real Estate",
    brokerPhone: "(401) 421-8888",
    sourcePlatform: "LoopNet",
    sourceUrl: null,
    daysListed: 180,
    status: "active",
    notes: "Zoned for multifamily up to 30 units. Shovel-ready.",
    rentRoll: null,
  },
];
